---
name: Prettier

on:
  push:
    branches: [main, monorepo]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run:
    name: Can the code be prettier? ðŸ¤”
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: lts/*
      - run: corepack enable
      - run: pnpm install --prefer-online --dev --ignore-scripts
      - uses: actions/cache@v3
        with:
          path: node_modules/.cache/prettier/.prettier-cache
          key: prettier-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('.prettierignore') }}-${{ hashFiles('.prettierrc.cjs') }}
      - run: prettier --cache --write .
      - run: git restore .github/workflows
      - uses: EndBug/add-and-commit@61a88be553afe4206585b31aa72387c64295d08b # tag=v9
        with:
          default_author: github_actions
          commit: --no-verify
          message: 'chore(prettier): ðŸ¤– âœ¨'
